### ISSUE TITLE
Marathon annotation filtering being ignored

### ISSUE THREAD

**Issue by msd117c** [Malinskiy/adam#111]
**Describe the bug**
After bumping the dependency to **0.5.4** the `blocklist` with `annotation` type stopped working.

**To Reproduce**
Add `blocklist` filtering option with `annotation` as `type`:
```yaml
...
filteringConfiguration:
  blocklist:
    - type: "annotation"
      values:
        - "com.example.Annotation"
```

**Expected behavior**
The annotated test classes should be ignored.

**Android device:**
 - Device: [Nexus 5X]
 - API: [33]
 - Adam Version [0.5.4]
- Android Debug Server Version [41]

**Additional context**
It was working on **0.5.3**.
